# Generated by Django 4.2.3 on 2023-08-27 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_business"),
    ]

    operations = [
        migrations.AlterModelTable(name="business", table="Business",),
    ]
